services:
  orchestrator:
    build: .
    command: uvicorn mini_snowflake.orchestrator.api:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./src:/app/src
    ports:
      - "8000:8000"

  worker:
    build: .
    command: uvicorn mini_snowflake.worker.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./src:/app/src
    environment:
      - ORCHESTRATOR_URL=http://orchestrator:8000
      - HEARTBEAT_SECONDS=5
    depends_on:
      - orchestrator
