[project]
name = "mini_snowflake_core"
version = "0.1.0"
description = "Core services for mini_snowflake"
requires-python = ">=3.11"
dependencies = [
  { path = "../../libs/core", develop = true },
  "click>=8.1"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"